spring.application.name=track-invoices
spring.profiles.active=dev

# Disable Flyway by default (enabled only in prod)
spring.flyway.enabled=false

# Configuration H2
spring.datasource.url=jdbc:h2:mem:trackdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Thymeleaf
spring.thymeleaf.cache=false

# Validation des messages en français par défaut
spring.messages.basename=messages
spring.messages.encoding=UTF-8
